version: "3.9"
name: ${NETWORK_STACK_NAME}-soc

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-restart: &default-restart
  restart: unless-stopped

networks:
  soc-net:

services:
  thehive:
    image: thehiveproject/thehive:5.2.2
    ports: [ "${THEHIVE_HTTP_PORT}:9000" ]
    networks: [ soc-net ]
    volumes:
      - ../configs/thehive/data:/opt/thp/thehive/data
      - ../configs/thehive/conf/application.conf:/etc/thehive/application.conf
    logging: *default-logging
    <<: *default-restart
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  cortex:
    image: thehiveproject/cortex:3.5.2
    ports: [ "${CORTEX_HTTP_PORT}:9001" ]
    networks: [ soc-net ]
    volumes:
      - ../configs/cortex/data:/opt/thp/cortex/data
      - ../configs/cortex/conf/application.conf:/etc/cortex/application.conf
    logging: *default-logging
    <<: *default-restart
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
