version: "3.9"
name: ${NETWORK_STACK_NAME}-ti

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-restart: &default-restart
  restart: unless-stopped

networks:
  frontend: {}
  backend: {}

services:
  misp:
    image: coolacid/misp-docker:${MISP_VERSION}
    ports: [ "${MISP_HTTPS_PORT}:443" ]
    logging: *default-logging
    <<: *default-restart
    networks: [frontend, backend]
    healthcheck:
      test: ["CMD", "curl", "-kfsS", "https://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 10
