version: "3.9"
name: ${NETWORK_STACK_NAME}-flows

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-restart: &default-restart
  restart: unless-stopped

networks:
  flows: {}

services:
  nprobe:
    image: ntop/nprobe:${NPROBE_VERSION}
    command: ["--collector-port", "${FLOW_COLLECTOR_PORT}", "--zmq", "tcp://*:5556"]
    network_mode: host     # for high-volume UDP
    logging: *default-logging
    <<: *default-restart
    healthcheck:
      test: ["CMD-SHELL", "ss -lun | grep -q :${FLOW_COLLECTOR_PORT}"]

  ntopng:
    image: ntop/ntopng:${NTOPNG_VERSION}
    command: ["-i", "tcp://127.0.0.1:5556"]
    ports: [ "${NTOPNG_HTTP_PORT}:3000" ]
    logging: *default-logging
    <<: *default-restart
    networks: [flows]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 10
