version: "3.9"
name: ${NETWORK_STACK_NAME}-soc

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-restart: &default-restart
  restart: unless-stopped

networks:
  frontend: {}
  backend: {}

services:
  thehive:
    image: strangebee/thehive:${THEHIVE_VERSION}
    ports: [ "${THEHIVE_HTTP_PORT}:9000" ]
    logging: *default-logging
    <<: *default-restart
    networks: [frontend, backend]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9000"]
      interval: 30s
      timeout: 5s
      retries: 10

  cortex:
    image: thehiveproject/cortex:${CORTEX_VERSION}
    ports: [ "${CORTEX_HTTP_PORT}:9001" ]
    logging: *default-logging
    <<: *default-restart
    networks: [frontend, backend]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9001"]
      interval: 30s
      timeout: 5s
      retries: 10
