version: "3.9"
name: ${NETWORK_STACK_NAME}-grafana

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

x-restart: &default-restart
  restart: unless-stopped

networks:
  grafana-net:

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    ports: [ "${GRAFANA_HTTP_PORT}:3001" ]
    networks: [ grafana-net ]
    volumes:
      - ../configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../configs/grafana/provisioning:/etc/grafana/provisioning
    logging: *default-logging
    <<: *default-restart
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 5s
      retries: 10
